dist: focal
language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11-dev"

install:
  - pip install pip --upgrade
  - pip install "poetry<1.2"
  - travis_retry poetry install

before_script:
  - export TZ=Asia/Tokyo
  - sudo ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
  - echo "Asia/Tokyo" > sudo tee /etc/timezone  > /dev/null
script:
   - make lint
   - poetry run pytest tests/test_local_*.py
branches:
  only:
  - main
cache: pip
