dist: focal
language: python
jobs:
  include:
    - python: 3.9
    - python: 3.10
      script:
        # 開発環境と同じPythonバージョンのときだけlintを実行する
        - make lint
    - python: 3.11
    - python: 3.12

install:
  - pip install pip --upgrade
  - pip install "poetry<1.8"
  - travis_retry poetry install --only main,linter,test

before_script:
  - export TZ=Asia/Tokyo
  - sudo ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
  - echo "Asia/Tokyo" > sudo tee /etc/timezone  > /dev/null

script:
   - poetry run pytest tests/test_local_*.py

branches:
  only:
    - main
cache: pip
